### ISSUE TITLE
添加多个header，报错java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by coder-luhao** [jianghejie/XRecyclerView#206]
实例化2个view，addHeaderView闪退，添加一个header不会报错，多个会报错，报错信息如下，请问是哪里的问题？？？

`java.lang.IllegalArgumentException: called detach on an already detached child ViewHolder{11ae0c3d position=2 id=-1, oldPos=-1, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
                                                                at android.support.v7.widget.RecyclerView$5.detachViewFromParent(RecyclerView.java:699)
                                                                at android.support.v7.widget.ChildHelper.detachViewFromParent(ChildHelper.java:284)
                                                                at android.support.v7.widget.RecyclerView$LayoutManager.detachViewInternal(RecyclerView.java:7243)
                                                                at android.support.v7.widget.RecyclerView$LayoutManager.detachViewAt(RecyclerView.java:7236)
                                                                at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:7641)
                                                                at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:7624)
                                                                at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:546)
                                                                at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
                                                                at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3075)
                                                                at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
                                                                at android.view.View.layout(View.java:16034)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                at com.zhy.autolayout.AutoLinearLayout.onLayout(AutoLinearLayout.java:50)
                                                                at android.view.View.layout(View.java:16034)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                at com.zhy.autolayout.AutoLinearLayout.onLayout(AutoLinearLayout.java:50)
                                                                at android.view.View.layout(View.java:16034)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                at android.support.v4.widget.NestedScrollView.onLayout(NestedScrollView.java:1622)
                                                                at android.view.View.layout(View.java:16034)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                at com.zhy.autolayout.AutoFrameLayout.onLayout(AutoFrameLayout.java:70)
                                                                at android.view.View.layout(View.java:16034)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1195)
                                                                at com.zhy.autolayout.AutoRelativeLayout.onLayout(AutoRelativeLayout.java:69)
                                                                at android.view.View.layout(View.java:16034)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                at android.view.View.layout(View.java:16034)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                at android.view.View.layout(View.java:16034)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                at com.zhy.autolayout.AutoFrameLayout.onLayout(AutoFrameLayout.java:70)
                                                                at android.view.View.layout(View.java:16034)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                at com.zhy.autolayout.AutoLinearLayout.onLayout(AutoLinearLayout.java:50)
                                                                at android.view.View.layout(View.java:16034)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                            	at `

**Comment by dakun666** [comment]
.inflate()第二个参数改为null，第三个参数删除或者改为null试一试

**Comment by coder-luhao** [comment]
这么做还是不行，我现在新建了一个XML文件代替多个header。

**Comment by zhangweicheng2013** [comment]
我也遇到这个问题了，求解答

**Comment by dakun666** [comment]
我这里使用
```
View view1 = LayoutInflater.from(activity).inflate(layoutId1, null);
View view2 = LayoutInflater.from(activity).inflate(layoutId2, null);
xRecyclerView.addHeaderView(view1);
xRecyclerView.addHeaderView(view2);
```
是没有问题的，两个都加上了。
@zhangweicheng2013 把代码和log贴上来，一起分析

**Comment by javyhoo** [comment]
我也遇到了这个问题，按照 @dakun666 的建议，第二个参数改为null，还是会闪退，求解答

headerview = new CustomizeHeaderLayout(this);
headerview1 = new CustomizeHeader1Layout(this);
headerview2 = new CustomizeHeader2Layout(this);

listview.addHeaderView(headerview);
listview.addHeaderView(headerview1);
listview.addHeaderView(headerview2);



public CustomizeHeaderLayout(Context context) {
        super(context);
        init();
}

private void init() {
  LayoutInflater inflater = (LayoutInflater)getContext().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
  View view = inflater.inflate(R.layout.layout_customize_headview, null);
  ...
}

02-28 14:16:40.905 18659-18659/ E/ACRA: fatal error : called detach on an already detached child ViewHolder{11eeac9 position=2 id=-1, oldPos=-1, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
                                                     java.lang.IllegalArgumentException: called detach on an already detached child ViewHolder{11eeac9 position=2 id=-1, oldPos=-1, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
                                                         at android.support.v7.widget.RecyclerView$5.detachViewFromParent(RecyclerView.java:756)
                                                         at android.support.v7.widget.ChildHelper.detachViewFromParent(ChildHelper.java:284)
                                                         at android.support.v7.widget.RecyclerView$LayoutManager.detachViewInternal(RecyclerView.java:7886)
                                                         at android.support.v7.widget.RecyclerView$LayoutManager.detachViewAt(RecyclerView.java:7879)
                                                         at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:8284)
                                                         at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:8267)
                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:553)
                                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3506)
                                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3254)
                                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3767)
                                                         at android.view.View.layout(View.java:17637)
                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                         at android.view.View.layout(View.java:17637)
                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                         at android.view.View.layout(View.java:17637)
                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                         at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
                                                         at android.view.View.layout(View.java:17637)
                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                         at android.view.View.layout(View.java:17637)
                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                         at android.view.View.layout(View.java:17637)
                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                         at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                                                         at android.view.View.layout(View.java:17637)
                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                         at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                         at android.os.Looper.loop(Looper.java:154)
                                                         at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by tingyouwu** [comment]
改一下源码吧  XRecycleView这个文件  
private List<Integer> sHeaderTypes = new ArrayList<>();//每个header必须有不同的type,不然滚动的时候顺序会变化

把static去掉

**Comment by dakun666** [comment]
你的意思是多个适配器的情况导致的么？

**Comment by tingyouwu** [comment]
对的  多个对象导致的 公用了一份headtype出错了

**Comment by dakun666** [comment]
但就算是静态的，每一份head存储的type也都是唯一的啊，没太明白，求解🙏

**Comment by tingyouwu** [comment]
但是如果是同时两个recycleview都add type  而你的type  private static final int HEADER_INIT_INDEX = 10002;  那就意味着肯定存在两个10003
