### ISSUE TITLE
操作控件滑动崩溃

### ISSUE THREAD

**Issue by greatcy** [jianghejie/XRecyclerView#293]
Process: com.xunlei.downloadprovider, PID: 23147
                                                   java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:0
                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:6720)
                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:6686)
                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1406)
                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                       at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1180)
                                                       at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1031)
                                                       at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1529)
                                                       at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2486)
                                                       at com.xunlei.downloadprovider.xlui.recyclerview.XRecyclerView.onTouchEvent(XRecyclerView.java:255)
                                                       at android.view.View.dispatchTouchEvent(View.java:10723)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2859)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2535)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
                                                       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:563)
                                                       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1870)
                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:3236)
                                                       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:525)
                                                       at android.view.View.dispatchPointerEvent(View.java:10952)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5121)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4973)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4504)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4557)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4523)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4656)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4531)
                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4713)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4504)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4557)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4523)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4531)

**Comment by TYUpya** [comment]
请问这个问题有解决吗？Is there any solution to this problem?
