### ISSUE TITLE
经常崩溃，崩溃错误如下

### ISSUE THREAD

**Issue by levianye** [jianghejie/XRecyclerView#44]
Caused by: java.lang.IllegalArgumentException: called detach on an already detached child ViewHolder{29d69d05 position=3 id=-1, oldPos=-1, pLpos:-1 scrap tmpDetached no parent}
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$4.detachViewFromParent(RecyclerView.java:605)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.support.v7.widget.ChildHelper.detachViewFromParent(ChildHelper.java:284)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$LayoutManager.detachViewInternal(RecyclerView.java:6473)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$LayoutManager.detachViewAt(RecyclerView.java:6466)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:6835)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:6818)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:532)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2847)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3145)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.view.View.layout(View.java:16542)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5302)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.view.View.layout(View.java:16542)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5302)
03-02 12:51:27.944 4119-4119/E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.view.View.layout(View.java:16542)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5302)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.view.View.layout(View.java:16542)
03-02 12:51:27.944 4119-4119/com.babytree.apps.pregnancy E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5302)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
03-02 12:51:27.944 4119-4119 E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.view.View.layout(View.java:16542)
03-02 12:51:27.944 4119-4119/com.babytree.apps.pregnancy E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5302)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.view.View.layout(View.java:16542)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5302)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
03-02 12:51:27.944 4119-4119/  E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.view.View.layout(View.java:16542)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5302)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
03-02 12:51:27.944 4119-4119/ E/AndroidRuntime:     at android.view.View.layout(View.java:16542)

**Comment by levianye** [comment]
不清楚到底是怎么引起的，错误堆栈也追溯不到我自己的APP这边，直接就是recyclerview的detachFromParent出错了，有谁遇到过么

**Comment by Allen-Cai** [comment]
我也遇到了相同的问题。。我这估计是我先从缓存中初始化轮播图addheader 然后网络加载回来后removeallviews再addheader引起的。把初始化缓存轮播图去掉了就好了
