### ISSUE TITLE
当数据量不足一页时，更换数据会造成崩溃

### ISSUE THREAD

**Issue by s7655120** [jianghejie/XRecyclerView#73]
崩溃日志如下：
05-12 22:40:31.098 7828-7828/com.youshixiu.gameshow E/ACRA: ACRA caught a IllegalArgumentException for com.youshixiu.gameshow
                                                            java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
                                                                at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:3586)
                                                                at android.support.v7.widget.RecyclerView$Recycler.quickRecycleScrapView(RecyclerView.java:3640)
                                                                at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:5492)
                                                                at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2086)
                                                                at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)
                                                                at android.view.View.layout(View.java:16630)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                at android.view.View.layout(View.java:16630)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                at android.view.View.layout(View.java:16630)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                at android.view.View.layout(View.java:16630)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                at android.view.View.layout(View.java:16630)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:148)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Ipoint** [comment]
我也遇到相同的问题，望快快修复

**Comment by e-hai** [comment]
好像很久没有更新了

**Comment by jianghejie** [comment]
话说是怎么更换数据的？

**Comment by luyoulong** [comment]
数据不足一页时 下拉刷新会崩溃  怎么解决了

**Comment by tigerleeli** [comment]
数据不足一页是 下拉刷新崩溃 求解决

**Comment by xiang473535976** [comment]
当数据量不足一页时，  删除item  获取的位置不准   删除第一个 还是最后一个 会崩溃！！1

**Comment by tanweijiu** [comment]
@xiang473535976  可以先考虑用notifydatachanged解决，我之前也试过，单个notifyRemove是有问题的
