### ISSUE TITLE
在下拉刷新的时候报错recyclerView Scrapped or attached views may not be recycled.。。。

### ISSUE THREAD

**Issue by Ipoint** [jianghejie/XRecyclerView#75]
item条目不够填充整个界面的时候，下拉刷新，就会报错recyclerView Scrapped or attached views may not be recycled.......有的时候是下拉几次会报这样的错

**Comment by gao746700783** [comment]
`java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
                                                 at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:4878)
                                                 at android.support.v7.widget.RecyclerView$Recycler.quickRecycleScrapView(RecyclerView.java:4951)
                                                 at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:7352)
                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3101)
                                                 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2917)
                                                 at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
                                                 at android.view.View.layout(View.java:15609)
                                                 at android.view.ViewGroup.layout(ViewGroup.java:4967)
                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                 at android.view.View.layout(View.java:15609)
                                                 at android.view.ViewGroup.layout(ViewGroup.java:4967)
                                                 at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
                                                 at android.view.View.layout(View.java:15609)
                                                 at android.view.ViewGroup.layout(ViewGroup.java:4967)
                                                 at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
                                                 at android.view.View.layout(View.java:15609)
                                                 at android.view.ViewGroup.layout(ViewGroup.java:4967)
                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                 at android.view.View.layout(View.java:15609)
                                                 at android.view.ViewGroup.layout(ViewGroup.java:4967)
                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                 at android.view.View.layout(View.java:15609)
                                                 at android.view.ViewGroup.layout(ViewGroup.java:4967)
                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                 at android.view.View.layout(View.java:15609)
                                                 at android.view.ViewGroup.layout(ViewGroup.java:4967)
                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                 at android.view.View.layout(View.java:15609)
                                                 at android.view.ViewGroup.layout(ViewGroup.java:4967)
                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                 at android.view.View.layout(View.java:15609)
                                                 at android.view.ViewGroup.layout(ViewGroup.java:4967)
                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                 at android.view.View.layout(View.java:15609)
                                                 at android.view.ViewGroup.layout(ViewGroup.java:4967)
                                                 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2123)
                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1880)
                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1075)
                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5853)
                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                 at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                 at android.os.Looper.loop(Looper.java:135)
                                                 at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)`

**Comment by gao746700783** [comment]
这个怎么解？

**Comment by AdleyLong** [comment]
我也遇到这个问题了

**Comment by gao746700783** [comment]
我的问题诡异的解决了，已经

**Comment by tigerleeli** [comment]
怎么解决的？？

**Comment by gao746700783** [comment]
加了一段代码，
`mCommonAdapter.notifyDataSetChanged();
        if (isRefresh) {
            mRvList.refreshComplete();
        } else {
            mRvList.loadMoreComplete();
        }`

**Comment by tigerleeli** [comment]
isRefresh 在这里吗  还是什么 不行呀     @Override
            public void onRefresh() {
                isRefresh=true;
                refresh();
            }

**Comment by gao746700783** [comment]
重点是，获取完数据以后的处理，
如果是刷新，则调用mRvList.refreshComplete()
如果是加载更多，则调用mRvList.loadMoreComplete();；

**Comment by luyoulong** [comment]
item条目不够填充整个界面的时候，下拉刷新我的一拉就崩溃

**Comment by gao746700783** [comment]
报错信息呢，也是上面这个吗？
再怎么着也不能直接崩溃吧

**Comment by luyoulong** [comment]
直接崩溃了啊 和上面的一样的啊 真的

**Comment by luyoulong** [comment]
错误和上面的一模一样

**Comment by gao746700783** [comment]
我这里以前崩溃过，后来按照我上面的处理，好了已经
实在不行的话，我把源码贴出来
而且，这个不是已经升级了吗，好像已经修复了这个bug，可以更新下版本


发自 网易邮箱大师
在2016年07月28日 01:01，luyoulong 写道:

直接崩溃了啊 和上面的一样的啊 真的

**Comment by sabobo** [comment]
直接崩溃，心碎

**Comment by gao746700783** [comment]
的确是


发自 网易邮箱大师
在2016年08月09日 17:32，BOB 写道:

直接崩溃，心碎

**Comment by ysemylord** [comment]
我也遇到这个问题了，解决了，情况是正这样的

错误写法
onRefresh(){
  list.clear（）
  网络请求();
}

解决
onRefresh(){
  网络请求(){
   list.clear()//将数组清空放在网络请求成功后
  }
}

推测原因：RecylcerView在执行头部回弹动画是会调整ReyclerView,此时将数组清空，导致错误

**Comment by Anthonyeef** [comment]
https://code.google.com/p/android/issues/detail?id=226353&can=1&q=reportedby%3DDeveloper%20-has%3Atriaged%20-has%3Apriority%20component%3DSupport-Libraries%20-has%3Ablocked&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened&start=1400

好像某种情况下，升级 support library 到 25 也会触发这个 crash。

我自己遇到的情况是，只有在 GridLayoutManager 的时候会发生。LinearLayoutManager 一切正常。

**Comment by walterFeng** [comment]
这个问题是因为下拉的过程中（手指抬起之前），你已经将adapter的数据清空了，但其实这个时候recyclerview也是需要不断刷新的数据显示的。修改方法。
  1.更新至 compile 'com.jcodecraeer:xrecyclerview:1.3.2'或者最新
  2.修改recyclerView的refresh()方法：
     recyclerView.refresh();
    @Override
    onRefresh() {
    //dataList.clear();//放在这里就会出现这个问题。
    HttpUtil.getData(new CallBack{
        onSuccess(Model modelList){
           dataList.clear();//应该放在这里。
           dataList.addAll(modelList);
           adapter.notifyDataSetChanged();
           recyclerView.refreshComplete();
        }
    },url);
｝

**Comment by androidjiawei** [comment]
我fix这个bug ，list.clear()方法应该在success中调用，在外部调用会报错。

**Comment by ThoughtRain** [comment]
我在这数据请求以后加上了 xRecyclerView.refreshComplete();还是会出现这个问题

**Comment by ZTFtrue** [comment]
> 我也遇到这个问题了，解决了，情况是正这样的
> 
> 错误写法
> onRefresh(){
> list.clear（）
> 网络请求();
> }
> 
> 解决
> onRefresh(){
> 网络请求(){
> list.clear()//将数组清空放在网络请求成功后
> }
> }
> 
> 推测原因：RecylcerView在执行头部回弹动画是会调整ReyclerView,此时将数组清空，导致错误

you are right.
